version: 2
jobs:
 build:
   branches:
    only:
     - master
     - develop
   machine: true
   steps:
     - checkout 

     # build image
     - run: |
         docker info
         docker build -t $IMAGE_NAME --file Stocky.Web/Dockerfile .

     # deploy the image
     - run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag $IMAGE_NAME registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME

     - run: |
           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
           docker push $IMAGE_NAME
            